import type {
  CommunityCourse,
  CommunityExercise,
  CommunityNotification,
  CommunityQuestion,
  CommunityReply,
  CommunityUser,
  VoteInfo,
} from "@/types/community.types";

const minutesAgo = (minutes: number) =>
  new Date(Date.now() - minutes * 60 * 1000).toISOString();

const hoursAgo = (hours: number) =>
  new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();

const daysAgo = (days: number) =>
  new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();

const makeVotes = (upvotes: number, downvotes: number, userVote: -1 | 0 | 1): VoteInfo => ({
  upvotes,
  downvotes,
  userVote,
});

export const currentCommunityUser: CommunityUser = {
  id: "u-current",
  name: "Sabrina",
  avatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=Sabrina",
  role: "student",
};

export const communityUsers: CommunityUser[] = [
  currentCommunityUser,
  {
    id: "u-mentor-1",
    name: "Daniel Ortiz",
    avatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=Daniel",
    role: "mentor",
  },
  {
    id: "u-student-1",
    name: "Ana Perez",
    avatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=Ana",
    role: "student",
  },
  {
    id: "u-student-2",
    name: "Marco Vega",
    avatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=Marco",
    role: "student",
  },
  {
    id: "u-mod-1",
    name: "Laura Morales",
    avatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=Laura",
    role: "moderator",
  },
  {
    id: "u-mentor-2",
    name: "Camila Rios",
    avatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=Camila",
    role: "mentor",
  },
];

export const communityCourses: CommunityCourse[] = [
  { id: "course-react", name: "Advanced React Patterns", genre: "Programming" },
  { id: "course-node", name: "Node.js API Architecture", genre: "Programming" },
  { id: "course-music", name: "Music Theory Fundamentals", genre: "Music" },
  { id: "course-audio", name: "Audio Mixing Essentials", genre: "Audio Engineering" },
  { id: "course-spanish", name: "Spanish A2", genre: "Languages" },
  { id: "course-business", name: "Startup Fundamentals", genre: "Business" },
];

export const communitySeasons = [
  { id: "season-1", name: "Season 1" },
  { id: "season-2", name: "Season 2" },
  { id: "season-3", name: "Season 3" },
];

export const communityExercises: CommunityExercise[] = [
  { id: "ex-react-hooks", courseId: "course-react", name: "Hooks Refactor Challenge" },
  { id: "ex-react-state", courseId: "course-react", name: "State Machine Exercise" },
  { id: "ex-node-auth", courseId: "course-node", name: "JWT Auth Practice" },
  { id: "ex-music-scales", courseId: "course-music", name: "Minor Scales Drill" },
  { id: "ex-audio-compression", courseId: "course-audio", name: "Compression Lab" },
  { id: "ex-spanish-verbs", courseId: "course-spanish", name: "Past Tense Quiz" },
  { id: "ex-business-pricing", courseId: "course-business", name: "Pricing Strategy Worksheet" },
];

export const mockQuestions: CommunityQuestion[] = [
  {
    id: "q-1",
    title: "When should I split a React component into custom hooks?",
    description:
      "I have a dashboard component that is growing a lot. It handles data fetching, filtering, and keyboard shortcuts. How do you decide when to split into custom hooks without over-engineering?",
    tags: ["react", "hooks", "architecture"],
    context: {
      courseId: "course-react",
      courseName: "Advanced React Patterns",
      seasonId: "season-2",
      seasonName: "Season 2",
      exerciseId: "ex-react-hooks",
      exerciseName: "Hooks Refactor Challenge",
      genre: "Programming",
    },
    author: currentCommunityUser,
    status: "solved",
    votes: makeVotes(42, 2, 1),
    repliesCount: 11,
    views: 1086,
    reports: 0,
    isLocked: false,
    acceptedReplyId: "r-2",
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(3),
  },
  {
    id: "q-2",
    title: "Best way to structure validation in Express for larger APIs?",
    description:
      "I am building a Node API with many endpoints. Should I use middleware-level schemas per route, or a domain-level validation layer? Looking for practical patterns.",
    tags: ["node", "express", "validation"],
    context: {
      courseId: "course-node",
      courseName: "Node.js API Architecture",
      genre: "Programming",
    },
    author: communityUsers[2],
    status: "open",
    votes: makeVotes(19, 1, 0),
    repliesCount: 6,
    views: 642,
    reports: 1,
    isLocked: false,
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(8),
  },
  {
    id: "q-3",
    title: "How to hear interval differences faster while training ear?",
    description:
      "I can identify major/minor thirds slowly but fail in real songs. Any routine that improved this for you?",
    tags: ["music", "ear-training", "practice"],
    context: {
      courseId: "course-music",
      courseName: "Music Theory Fundamentals",
      exerciseId: "ex-music-scales",
      exerciseName: "Minor Scales Drill",
      genre: "Music",
    },
    author: communityUsers[3],
    status: "open",
    votes: makeVotes(13, 0, 0),
    repliesCount: 4,
    views: 390,
    reports: 0,
    isLocked: false,
    createdAt: hoursAgo(16),
    updatedAt: hoursAgo(4),
  },
  {
    id: "q-4",
    title: "My compressor settings pump too much, what should I adjust first?",
    description:
      "On vocals I hear obvious pumping. Ratio is 6:1 with fast attack. Should I start by reducing ratio or changing release?",
    tags: ["audio", "compression", "mixing"],
    context: {
      courseId: "course-audio",
      courseName: "Audio Mixing Essentials",
      exerciseId: "ex-audio-compression",
      exerciseName: "Compression Lab",
      genre: "Audio Engineering",
    },
    author: communityUsers[1],
    status: "open",
    votes: makeVotes(24, 1, -1),
    repliesCount: 8,
    views: 711,
    reports: 0,
    isLocked: false,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
  },
  {
    id: "q-5",
    title: "How to remember Spanish irregular preterite verbs?",
    description:
      "I always forget forms like tener/tener or estar/estar in preterite. Looking for memorization techniques that actually stick.",
    tags: ["spanish", "verbs", "study-technique"],
    context: {
      courseId: "course-spanish",
      courseName: "Spanish A2",
      exerciseId: "ex-spanish-verbs",
      exerciseName: "Past Tense Quiz",
      genre: "Languages",
    },
    author: communityUsers[2],
    status: "open",
    votes: makeVotes(8, 0, 0),
    repliesCount: 2,
    views: 233,
    reports: 0,
    isLocked: false,
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(2),
  },
  {
    id: "q-6",
    title: "Thread locked example: pricing template confusion",
    description:
      "This thread was locked by moderation after repeated off-topic comments. Keeping it as reference for policy behavior.",
    tags: ["business", "moderation"],
    context: {
      courseId: "course-business",
      courseName: "Startup Fundamentals",
      exerciseId: "ex-business-pricing",
      exerciseName: "Pricing Strategy Worksheet",
      genre: "Business",
    },
    author: communityUsers[4],
    status: "locked",
    votes: makeVotes(5, 2, 0),
    repliesCount: 0,
    views: 150,
    reports: 0,
    isLocked: true,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(6),
  },
];

export const mockReplies: CommunityReply[] = [
  {
    id: "r-1",
    questionId: "q-1",
    body: "A practical threshold: if one concern can be tested independently, move it to a hook. Keep UI state in component, cross-cutting behavior in hooks.",
    author: communityUsers[1],
    votes: makeVotes(16, 0, 1),
    reports: 0,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "r-2",
    questionId: "q-1",
    body: "I use 3 checks: 1) repeated logic in 2+ components, 2) side effects mixed with rendering, 3) component exceeds one screen of logic. If two checks are true, extract hook.",
    author: communityUsers[5],
    votes: makeVotes(30, 0, 0),
    reports: 0,
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(5),
  },
  {
    id: "r-3",
    questionId: "q-1",
    parentReplyId: "r-2",
    parentAuthorName: "Camila Rios",
    body: "This checklist is gold. Do you separate API calls and derived filtering into different hooks?",
    author: communityUsers[3],
    votes: makeVotes(7, 0, 0),
    reports: 0,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "r-4",
    questionId: "q-1",
    parentReplyId: "r-3",
    parentAuthorName: "Marco Vega",
    body: "Yes. One hook for transport/data state and another hook for pure computed filters. It keeps effects very explicit.",
    author: communityUsers[5],
    votes: makeVotes(11, 0, 0),
    reports: 0,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "r-5",
    questionId: "q-1",
    body: "I made a mini rule: hooks should return either state+actions or a computed model, not both.",
    author: communityUsers[2],
    votes: makeVotes(8, 1, 0),
    reports: 0,
    createdAt: hoursAgo(22),
    updatedAt: hoursAgo(22),
  },
  {
    id: "r-6",
    questionId: "q-1",
    parentReplyId: "r-5",
    parentAuthorName: "Ana Perez",
    body: "That is a nice rule. I ended up mixing both and maintenance got painful.",
    author: currentCommunityUser,
    votes: makeVotes(4, 0, 0),
    reports: 0,
    createdAt: minutesAgo(12),
    updatedAt: minutesAgo(12),
  },
  {
    id: "r-7",
    questionId: "q-2",
    body: "Go with schema-per-route + shared schema fragments. Domain validation for business rules only.",
    author: communityUsers[1],
    votes: makeVotes(9, 0, 0),
    reports: 0,
    createdAt: hoursAgo(14),
    updatedAt: hoursAgo(14),
  },
  {
    id: "r-8",
    questionId: "q-2",
    parentReplyId: "r-7",
    parentAuthorName: "Daniel Ortiz",
    body: "Agree. Keep transport validation close to controllers. Business rules should not know about HTTP.",
    author: communityUsers[5],
    votes: makeVotes(6, 0, 0),
    reports: 0,
    createdAt: hoursAgo(12),
    updatedAt: hoursAgo(12),
  },
  {
    id: "r-9",
    questionId: "q-3",
    body: "Train with short loops: identify interval, sing it, then verify on instrument. 15 minutes daily beats long sessions.",
    author: communityUsers[1],
    votes: makeVotes(10, 0, 0),
    reports: 0,
    createdAt: hoursAgo(10),
    updatedAt: hoursAgo(10),
  },
  {
    id: "r-10",
    questionId: "q-4",
    body: "Start with release. Too fast release causes audible pumping tails. Try slower release and lower ratio to 3:1 first.",
    author: communityUsers[5],
    votes: makeVotes(15, 0, 1),
    reports: 0,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: "r-11",
    questionId: "q-4",
    parentReplyId: "r-10",
    parentAuthorName: "Camila Rios",
    body: "Also check input level into compressor. Hitting too hard can exaggerate pumping regardless of settings.",
    author: communityUsers[3],
    votes: makeVotes(5, 0, 0),
    reports: 0,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "r-12",
    questionId: "q-5",
    body: "Group irregulars by stem changes and drill with spaced repetition cards. Use tiny daily sessions.",
    author: communityUsers[2],
    votes: makeVotes(4, 0, 0),
    reports: 0,
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(4),
  },
];

export const mockNotifications: CommunityNotification[] = [
  {
    id: "n-1",
    type: "reply_question",
    questionId: "q-1",
    replyId: "r-5",
    actorName: "Ana Perez",
    message: "Ana replied to your question.",
    isRead: false,
    createdAt: hoursAgo(22),
  },
  {
    id: "n-2",
    type: "accepted_answer",
    questionId: "q-1",
    replyId: "r-2",
    actorName: "Sabrina",
    message: "Your answer was marked as accepted.",
    isRead: false,
    createdAt: hoursAgo(3),
  },
  {
    id: "n-3",
    type: "reply_comment",
    questionId: "q-2",
    replyId: "r-8",
    actorName: "Camila Rios",
    message: "Camila replied to your comment.",
    isRead: true,
    createdAt: hoursAgo(12),
  },
];
