import type { Resource } from "@/types/resource.types";

export const mockResources: Resource[] = [
  {
    id: "1",
    title: "Complete JavaScript ES6+ Guide",
    description: "A comprehensive guide covering all modern JavaScript features including arrow functions, async/await, destructuring, and more.",
    genre: ["Programming"],
    resourceType: "PDF",
    tags: ["javascript", "es6", "programming"],
    difficultyLevel: "Intermediate",
    status: "Published",
    authorId: "user1",
    authorName: "John Doe",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    fileUrl: "/resources/pdfs/javascript-es6-guide.pdf",
    fileName: "javascript-es6-guide.pdf",
    fileSize: 5242880, // 5MB
    thumbnailUrl: "https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=400&h=300&fit=crop",
    views: 1250,
    downloads: 340,
    rating: 4.8,
    ratingCount: 89,
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
    publishedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    title: "Music Theory Fundamentals",
    description: "Learn the basics of music theory including scales, chords, rhythm, and harmony. Perfect for beginners.",
    genre: ["Music"],
    resourceType: "Video",
    tags: ["music", "theory", "beginner"],
    difficultyLevel: "Beginner",
    status: "Published",
    authorId: "user2",
    authorName: "Sarah Johnson",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoDuration: "45:32",
    thumbnailUrl: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=300&fit=crop",
    views: 3450,
    downloads: 0,
    rating: 4.9,
    ratingCount: 156,
    createdAt: "2024-02-01T14:20:00Z",
    updatedAt: "2024-02-01T14:20:00Z",
    publishedAt: "2024-02-01T14:20:00Z",
  },
  {
    id: "3",
    title: "Python Programming Practice Exercises",
    description: "50 challenging Python exercises covering data structures, algorithms, and problem-solving techniques.",
    genre: ["Programming"],
    resourceType: "Exercise",
    tags: ["python", "exercises", "practice"],
    difficultyLevel: "Advanced",
    status: "Published",
    authorId: "user3",
    authorName: "Mike Chen",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
    exercise: {
      questions: [
        {
          id: "q1",
          type: "Multiple Choice",
          question: "What is the output of print(type([]))?",
          options: ["<class 'list'>", "<class 'dict'>", "<class 'tuple'>", "<class 'set'>"],
          correctAnswer: "<class 'list'>",
        },
        {
          id: "q2",
          type: "True/False",
          question: "Python is a statically typed language.",
          correctAnswer: false,
        },
      ],
      totalPoints: 100,
      timeLimit: 60,
      passingScore: 70,
    },
    thumbnailUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&h=300&fit=crop",
    views: 890,
    downloads: 230,
    rating: 4.6,
    ratingCount: 67,
    createdAt: "2024-02-10T09:15:00Z",
    updatedAt: "2024-02-10T09:15:00Z",
    publishedAt: "2024-02-10T09:15:00Z",
  },
  {
    id: "4",
    title: "Audio Mixing and Mastering Techniques",
    description: "Professional techniques for mixing and mastering audio tracks to achieve commercial quality sound.",
    genre: ["Audio Engineering", "Music"],
    resourceType: "PDF",
    tags: ["audio", "mixing", "mastering", "production"],
    difficultyLevel: "Expert",
    status: "Published",
    authorId: "user4",
    authorName: "Alex Rodriguez",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    fileUrl: "/resources/pdfs/audio-mixing-mastering.pdf",
    fileName: "audio-mixing-mastering.pdf",
    fileSize: 15728640, // 15MB
    thumbnailUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=400&h=300&fit=crop",
    views: 650,
    downloads: 180,
    rating: 4.7,
    ratingCount: 45,
    createdAt: "2024-02-15T16:45:00Z",
    updatedAt: "2024-02-15T16:45:00Z",
    publishedAt: "2024-02-15T16:45:00Z",
  },
  {
    id: "5",
    title: "Digital Marketing Strategies 2024",
    description: "Learn the latest digital marketing strategies including SEO, social media marketing, content marketing, and analytics.",
    genre: ["Business", "Marketing"],
    resourceType: "Video",
    tags: ["marketing", "digital", "seo", "social-media"],
    difficultyLevel: "Intermediate",
    status: "Published",
    authorId: "user5",
    authorName: "Emily Davis",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
    youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoDuration: "1:25:15",
    thumbnailUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop",
    views: 2340,
    downloads: 0,
    rating: 4.5,
    ratingCount: 112,
    createdAt: "2024-02-20T11:30:00Z",
    updatedAt: "2024-02-20T11:30:00Z",
    publishedAt: "2024-02-20T11:30:00Z",
  },
  {
    id: "6",
    title: "Spanish Grammar Exercises for Beginners",
    description: "Interactive exercises to practice Spanish grammar, verb conjugations, and sentence structure.",
    genre: ["Languages"],
    resourceType: "Exercise",
    tags: ["spanish", "grammar", "language-learning"],
    difficultyLevel: "Beginner",
    status: "Published",
    authorId: "user6",
    authorName: "Carlos Martinez",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
    exercise: {
      questions: [
        {
          id: "q1",
          type: "Multiple Choice",
          question: "What is the Spanish word for 'hello'?",
          options: ["Adiós", "Hola", "Gracias", "Por favor"],
          correctAnswer: "Hola",
        },
      ],
      totalPoints: 50,
      timeLimit: 30,
      passingScore: 60,
    },
    thumbnailUrl: "https://images.unsplash.com/photo-1543109740-4bdb38fda756?w=400&h=300&fit=crop",
    views: 1560,
    downloads: 420,
    rating: 4.8,
    ratingCount: 95,
    createdAt: "2024-02-25T08:00:00Z",
    updatedAt: "2024-02-25T08:00:00Z",
    publishedAt: "2024-02-25T08:00:00Z",
  },
  {
    id: "7",
    title: "UI/UX Design Principles",
    description: "Essential design principles for creating intuitive and beautiful user interfaces and experiences.",
    genre: ["Design"],
    resourceType: "PDF",
    tags: ["design", "ui", "ux", "principles"],
    difficultyLevel: "Intermediate",
    status: "Published",
    authorId: "user7",
    authorName: "Jessica Lee",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica",
    fileUrl: "/resources/pdfs/ui-ux-principles.pdf",
    fileName: "ui-ux-principles.pdf",
    fileSize: 8388608, // 8MB
    thumbnailUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=300&fit=crop",
    views: 2100,
    downloads: 550,
    rating: 4.9,
    ratingCount: 134,
    createdAt: "2024-03-01T13:20:00Z",
    updatedAt: "2024-03-01T13:20:00Z",
    publishedAt: "2024-03-01T13:20:00Z",
  },
  {
    id: "8",
    title: "Introduction to Quantum Physics",
    description: "A beginner-friendly introduction to quantum physics concepts, experiments, and applications.",
    genre: ["Science"],
    resourceType: "Video",
    tags: ["physics", "quantum", "science"],
    difficultyLevel: "Beginner",
    status: "Published",
    authorId: "user8",
    authorName: "Dr. Robert Williams",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Robert",
    youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoDuration: "52:48",
    thumbnailUrl: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&h=300&fit=crop",
    views: 1800,
    downloads: 0,
    rating: 4.7,
    ratingCount: 88,
    createdAt: "2024-03-05T10:10:00Z",
    updatedAt: "2024-03-05T10:10:00Z",
    publishedAt: "2024-03-05T10:10:00Z",
  },
  {
    id: "9",
    title: "Calculus Problem Set - Derivatives",
    description: "Comprehensive problem set covering derivatives, limits, and applications in calculus.",
    genre: ["Mathematics"],
    resourceType: "Exercise",
    tags: ["math", "calculus", "derivatives"],
    difficultyLevel: "Advanced",
    status: "Published",
    authorId: "user9",
    authorName: "Prof. Linda Brown",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Linda",
    exercise: {
      questions: [
        {
          id: "q1",
          type: "Open-Ended",
          question: "Find the derivative of f(x) = 3x^2 + 2x + 1",
        },
      ],
      totalPoints: 100,
      timeLimit: 90,
      passingScore: 75,
    },
    thumbnailUrl: "https://images.unsplash.com/photo-1635372722656-389f87a941b7?w=400&h=300&fit=crop",
    views: 980,
    downloads: 270,
    rating: 4.6,
    ratingCount: 54,
    createdAt: "2024-03-08T15:30:00Z",
    updatedAt: "2024-03-08T15:30:00Z",
    publishedAt: "2024-03-08T15:30:00Z",
  },
  {
    id: "10",
    title: "Watercolor Painting Techniques",
    description: "Learn essential watercolor painting techniques including wet-on-wet, dry brush, and color mixing.",
    genre: ["Arts"],
    resourceType: "Video",
    tags: ["art", "painting", "watercolor"],
    difficultyLevel: "Beginner",
    status: "Published",
    authorId: "user10",
    authorName: "Anna Thompson",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Anna",
    youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoDuration: "38:25",
    thumbnailUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=300&fit=crop",
    views: 2750,
    downloads: 0,
    rating: 4.9,
    ratingCount: 178,
    createdAt: "2024-03-10T09:45:00Z",
    updatedAt: "2024-03-10T09:45:00Z",
    publishedAt: "2024-03-10T09:45:00Z",
  },
];
