import type { StudentGrade, EarningsBreakdown, PayoutHistory, EngagementMetrics, ExamOverview, DashboardAlert } from "@/types/professor.types";

// Mock professor data
export const mockProfessor = {
  id: "prof-001",
  userId: "user-001",
  name: "Dr. Sarah Chen",
  email: "sarah.chen@skillmind.com",
  bio: "Expert in React, Web Development, and Software Architecture with 15+ years of experience.",
  avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
  verificationStatus: "verified" as const,
  createdAt: "2023-01-15T10:00:00Z",
  updatedAt: "2024-03-20T14:30:00Z",
};

// Mock grades data
export const mockStudentGrades: StudentGrade[] = [
  {
    id: "grade-001",
    studentId: "student-001",
    studentName: "Alex Johnson",
    courseId: "course-001",
    courseName: "React Performance Mastery",
    examId: "exam-001",
    examName: "Midterm Exam",
    score: 85,
    maxScore: 100,
    percentage: 85,
    status: "completed",
    isAutoGraded: true,
    publishedAt: "2024-03-18T10:00:00Z",
    submittedAt: "2024-03-17T15:30:00Z",
    feedback: "Excellent performance on async rendering concepts.",
    questions: [
      {
        id: "q1",
        questionText: "What does React.memo do?",
        studentAnswer: "Prevents unnecessary re-renders",
        correctAnswer: "Prevents unnecessary re-renders",
        isCorrect: true,
        points: 10,
        maxPoints: 10,
      },
      {
        id: "q2",
        questionText: "Explain useCallback hook",
        studentAnswer: "Memoizes functions to prevent recreation",
        correctAnswer: "Memoizes functions to prevent recreation",
        isCorrect: true,
        points: 15,
        maxPoints: 15,
      },
    ],
  },
  {
    id: "grade-002",
    studentId: "student-002",
    studentName: "Maria Rodriguez",
    courseId: "course-001",
    courseName: "React Performance Mastery",
    examId: "exam-001",
    examName: "Midterm Exam",
    score: 92,
    maxScore: 100,
    percentage: 92,
    status: "completed",
    isAutoGraded: true,
    publishedAt: "2024-03-18T10:00:00Z",
    submittedAt: "2024-03-17T14:00:00Z",
  },
  {
    id: "grade-003",
    studentId: "student-003",
    studentName: "John Smith",
    courseId: "course-002",
    courseName: "Advanced TypeScript",
    examId: "exam-002",
    examName: "Final Project Review",
    score: 78,
    maxScore: 100,
    percentage: 78,
    status: "pending",
    isAutoGraded: false,
    submittedAt: "2024-03-19T16:45:00Z",
    feedback: "Awaiting manual review",
  },
  {
    id: "grade-004",
    studentId: "student-004",
    studentName: "Emily Watson",
    courseId: "course-002",
    courseName: "Advanced TypeScript",
    examId: "exam-003",
    examName: "Quiz 1",
    score: 88,
    maxScore: 100,
    percentage: 88,
    status: "completed",
    isAutoGraded: true,
    publishedAt: "2024-03-19T09:00:00Z",
    submittedAt: "2024-03-19T08:30:00Z",
  },
];

// Mock earnings data
export const mockEarningsBreakdown: EarningsBreakdown = {
  totalEarnings: 24500,
  perCourse: {
    "course-001": 15000,
    "course-002": 8200,
    "course-003": 1300,
  },
  netAmount: 22050,
  platformFees: 2450,
  totalPayouts: 18000,
  pendingAmount: 4050,
};

// Mock payout history
export const mockPayoutHistory: PayoutHistory = {
  payouts: [
    {
      id: "payout-001",
      amount: 5000,
      status: "paid",
      date: "2024-02-15T00:00:00Z",
      method: "bank_transfer",
      transactionId: "TXN-2024-02-15-001",
    },
    {
      id: "payout-002",
      amount: 6500,
      status: "paid",
      date: "2024-01-15T00:00:00Z",
      method: "bank_transfer",
      transactionId: "TXN-2024-01-15-001",
    },
    {
      id: "payout-003",
      amount: 4050,
      status: "processing",
      date: "2024-03-20T00:00:00Z",
      dueDate: "2024-04-05T00:00:00Z",
      method: "bank_transfer",
    },
    {
      id: "payout-004",
      amount: 2500,
      status: "pending",
      date: "2024-04-10T00:00:00Z",
      dueDate: "2024-05-15T00:00:00Z",
      method: "stripe",
    },
  ],
  totalPaid: 11500,
  totalPending: 6550,
  nextPayoutDate: "2024-04-15T00:00:00Z",
};

// Mock engagement metrics
export const mockEngagementMetrics: EngagementMetrics[] = [
  {
    courseId: "course-001",
    courseName: "React Performance Mastery",
    averageWatchTime: 145,
    completionRate: 78,
    dropOffPoints: [
      {
        lessonId: "lesson-005",
        lessonTitle: "Advanced State Management",
        dropoffPercentage: 22,
        position: 5,
      },
      {
        lessonId: "lesson-012",
        lessonTitle: "Profiling & Debugging",
        dropoffPercentage: 15,
        position: 12,
      },
    ],
    mostReWatchedSections: [
      {
        sectionId: "section-001",
        sectionTitle: "React Hook Fundamentals",
        reWatchCount: 145,
        averageReWatchTime: 8,
      },
      {
        sectionId: "section-003",
        sectionTitle: "useCallback Deep Dive",
        reWatchCount: 98,
        averageReWatchTime: 6,
      },
    ],
    exerciseParticipationRate: 85,
    questionActivityCount: 342,
    activeStudentCount: 156,
    totalStudentCount: 203,
  },
  {
    courseId: "course-002",
    courseName: "Advanced TypeScript",
    averageWatchTime: 132,
    completionRate: 72,
    dropOffPoints: [
      {
        lessonId: "lesson-008",
        lessonTitle: "Advanced Generics",
        dropoffPercentage: 28,
        position: 8,
      },
    ],
    mostReWatchedSections: [
      {
        sectionId: "section-002",
        sectionTitle: "Type System Basics",
        reWatchCount: 87,
        averageReWatchTime: 10,
      },
    ],
    exerciseParticipationRate: 72,
    questionActivityCount: 218,
    activeStudentCount: 89,
    totalStudentCount: 125,
  },
];

// Mock exam overviews
export const mockExamOverviews: ExamOverview[] = [
  {
    examId: "exam-001",
    examName: "Midterm Exam",
    courseId: "course-001",
    courseName: "React Performance Mastery",
    type: "multiple_choice",
    totalAttempts: 203,
    passCount: 167,
    failCount: 36,
    passRate: 82,
    averageScore: 81.5,
    medianScore: 84,
    createdAt: "2024-02-01T00:00:00Z",
  },
  {
    examId: "exam-002",
    examName: "Final Project Review",
    courseId: "course-002",
    courseName: "Advanced TypeScript",
    type: "mixed",
    totalAttempts: 125,
    passCount: 98,
    failCount: 27,
    passRate: 78,
    averageScore: 76.2,
    medianScore: 78,
    createdAt: "2024-02-15T00:00:00Z",
  },
  {
    examId: "exam-003",
    examName: "Quiz 1",
    courseId: "course-002",
    courseName: "Advanced TypeScript",
    type: "multiple_choice",
    totalAttempts: 125,
    passCount: 119,
    failCount: 6,
    passRate: 95,
    averageScore: 88.3,
    medianScore: 90,
    createdAt: "2024-03-01T00:00:00Z",
  },
];

// Mock alerts
export const mockAlerts: DashboardAlert[] = [
  {
    id: "alert-001",
    type: "unreviewed_exam",
    title: "3 Exams Pending Review",
    description: "3 students submitted exams awaiting your manual review in Advanced TypeScript",
    severity: "warning",
    actionUrl: "/professor/grades?status=pending",
    actionLabel: "Review Exams",
    createdAt: "2024-03-20T09:30:00Z",
  },
  {
    id: "alert-002",
    type: "low_engagement",
    title: "Low Engagement Alert",
    description: "Completion rate dropped to 68% in Web Dev 101. Consider reaching out to inactive students.",
    severity: "warning",
    actionUrl: "/professor/analytics",
    actionLabel: "View Analytics",
    createdAt: "2024-03-19T14:00:00Z",
  },
  {
    id: "alert-003",
    type: "certification",
    title: "5 Students Completed Certification",
    description: "5 students are now eligible for certificates in React Performance Mastery",
    severity: "info",
    actionUrl: "/professor/certifications",
    actionLabel: "Issue Certificates",
    createdAt: "2024-03-18T11:00:00Z",
    readAt: "2024-03-18T16:30:00Z",
  },
];
